// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://raztmhzhqastebygwjwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhenRtaHpocWFzdGVieWd3anduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MjA4MDUsImV4cCI6MjA1OTI5NjgwNX0.NviQEJUY4D7YyzdqrMFDfwH7_4WxgrVpCOOhDHoTg20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);